# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_Main_Img',
            field=models.FileField(upload_to='log_Files/'),
        ),
    ]
