# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190622_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_File', models.FileField(upload_to='log_Files/')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
